"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
const install = require("../utils/vue/install.js");
require("vue");
require("../utils/types.js");
const popper_vue_vue_type_script_setup_true_name_EtuPopperRoot_lang = require("./src/popper.vue.js");
const popper = require("./src/popper.js");
console.log(popper_vue_vue_type_script_setup_true_name_EtuPopperRoot_lang, "opper");
const EtuPopper = install.withInstall(popper_vue_vue_type_script_setup_true_name_EtuPopperRoot_lang);
exports.popperProps = popper.popperProps;
exports.roleTypes = popper.roleTypes;
exports.EtuPopper = EtuPopper;
exports.default = EtuPopper;
